name: ng_c1
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - jupyter
  - ipykernel
  - ipywidgets
  - ipympl
  - notebook
  - pip
  - pip:
      - debugpy
